/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdoptionRequestSchema extends BaseModel {
  static $columns = ['animalId', 'createdAt', 'dataVisita', 'email', 'horarioVisita', 'id', 'mensagem', 'motivoCancelamento', 'nome', 'status', 'telefone', 'updatedAt'] as const
  $columns = AdoptionRequestSchema.$columns
  @column()
  declare animalId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dataVisita: DateTime
  @column()
  declare email: string
  @column()
  declare horarioVisita: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mensagem: string | null
  @column()
  declare motivoCancelamento: string | null
  @column()
  declare nome: string
  @column()
  declare status: string
  @column()
  declare telefone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AnimalSchema extends BaseModel {
  static $columns = ['ativa', 'createdAt', 'descricao', 'especie', 'fotoUrl', 'id', 'idade', 'porte', 'sexo', 'titulo', 'updatedAt'] as const
  $columns = AnimalSchema.$columns
  @column()
  declare ativa: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descricao: string | null
  @column()
  declare especie: string
  @column()
  declare fotoUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idade: string
  @column()
  declare porte: string
  @column()
  declare sexo: string
  @column()
  declare titulo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
